name: Build and push Docker image

on:
  push:
    tags:
      - "*.*.*"

env:
  IMAGE_VERSION: ${{ vars.NGINX_VERSION }}-${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          build-args: |
            ENTRYPOINT_SCRIPTS_VERSION=${{ vars.ENTRYPOINT_SCRIPTS_VERSION }}
            IMAGE_REVISION=${{ github.sha }}
            IMAGE_VERSION=${{ env.IMAGE_VERSION }}
            NGINX_VERSION=${{ vars.NGINX_VERSION }}
            UPLOAD_MODULE_COMMIT=${{ vars.UPLOAD_MODULE_COMMIT }}
            UPLOAD_MODULE_REPO=${{ vars.UPLOAD_MODULE_REPO }}
          context: .
          file: ./Dockerfile
          push: true
          tags: cytomineuliege/nginx:${{ env.IMAGE_VERSION }}
